obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.235, 0.380], [0.235, -0.380], [-0.235, -0.380], [-0.235, 0.380]]
inflation_radius: 0.4
observation_sources: pointcloud_sensor
pointcloud_sensor: {
                      sensor_frame: camera_link, 
                      data_type: PointCloud2, 
                      topic: /rtabmap/cloud_map,
                      marking: true, 
                      clearing: true
                   }
