# params for the joint_state_publisher package
# (only used in view_urdf.launch)
rate: 50
check_limits: false
sources: [joints/camera, joints/wheels]
zero_positions: true
zero_velocities: true
zero_efforts: false