frequency: 10
sensor_timeout: 0.1
two_d_mode: true
print_diagnostics: true
debug: true
publish_acceleration: false

odom0: "wheels/odom"
# x, y, z, 
# roll, pitch, yaw,
# vx, vy, vz, 
# vroll, vpitch, vyaw, 
# ax, ay, az
odom0_config: [ false, false, false,
                false, false, false,
                true, true, false,
                false, false, true,
                false, false, false ]

odom0_queue_size: 30
odom0_differential: false

odom1: "camera/odom"
odom1_config: [true,  true,  true,
               false, false, false,
               false, false, true,
               false, false, false,
               false, false, false]

odom1_queue_size: 30
odom1_differential: false

imu0: imu/data
imu0_config: [ false, false, false,
               true,  true,  true,
               false, false, false,
               true,  true,  true,
               true,  false,  true ]

imu0_queue_size: 30
imu0_remove_gravitational_acceleration: true
imu0_differential: false
imu0_relative: true
use_control: false